### ISSUE TITLE
navigation android dans l'application 

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/openradiation-mobile#11]
Note Ghislain : 
Paramètres / Liste des capteurs bluetooth : si je clique sur retour arrière Android plutôt que le retour arrière de l’application, j’ai sur la page d’accueil « aucun capteur » alors que je viens de me connecter.

Note PHL : pas sur que ce soit faisable de manière raisonable

**Comment by vm-agoralogie** [comment]
Désactivation du comportement du bouton back android.
Semble fonctionner sur tablette samsung (ne perturbe pas le comportement du bouton back dans inAppBrowser)
