### ISSUE TITLE
appel API suite saisie manuelle

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/openradiation-mobile#16]
Saisie manuelle : Dans les données envoyées à l’API on a  apparatusId":"undefined","apparatusVersion":"undefined","apparatusSensorType":"geiger","apparatusTubeType":"undefined". Normalement ces 4 champs devraient ne pas être envoyés.

**Comment by pmlaroche-agoralogie** [comment]
Note PHL : on peut dire qu'on n'envoie jamais les valeurs undefined ?

**Comment by ghisd** [comment]
Il ne faut pas que les propriétés de l'objet json soient définies du tout. Il ne faut pas envoyer de propriété apparatusId, apparatusVersion, apparatusSensorType ou apparatusTubeType dans le cas d'une saisie maunelle.
Oui de manière générale, si undefined, il vaut mieux ne rien envoyer du tout.
