### ISSUE TITLE
id montrée/ envoyée

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/openradiation-mobile#20]
Ecran d’accueil / capteur ID : l’ID indiqué n’est pas le même sous Android et sous Iphone pour un même capteur.  D’ailleurs je pense que l’on devrait afficher et transmettre à l’API le nom du capteur (tel qu’il est indiqué lorsque l’on se connecte  plutôt que son ID

![accueiliphone](https://cloud.githubusercontent.com/assets/547222/18951976/3087097e-8648-11e6-9802-2a838b144686.jpg)

![nomcapteur](https://cloud.githubusercontent.com/assets/547222/18951964/1da384cc-8648-11e6-8037-5203877b2c31.png)
![accueilandroid](https://cloud.githubusercontent.com/assets/547222/18951972/2655ab68-8648-11e6-8f15-e669ca1ffffd.png)

**Comment by pmlaroche-agoralogie** [comment]
on n'a sans doute pas d'option pour contourner l'OS pour avoir un numero unique. Mais il serait pertinent d'envoyer, avec la mesure, une concaténation (avec séprateur ; ) dans une string de 
MODEL puis VERSION puis SERIAL_NUMBER

**Comment by vm-agoralogie** [comment]
Serial dans advertising au listage des devices.
Concatenation: name+version+advertising dans champ version.
