### ISSUE TITLE
liste de device bluetooth connectables

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/openradiation-mobile#28]
lorsque il  y a deux devices bluetooth à portée, les noms des deux devices sont superposés, on a l'impression que le second vient s'afficher sur le premier.

**Comment by vm-exalgebra** [comment]
Non reproduit en local.
Besoin de deux capteurs pour tester sur devices.

**Comment by vm-agoralogie** [comment]
Non reproduit en local.
Besoin de deux capteurs pour tester sur devices.
