### ISSUE TITLE
sensibilité gps

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/openradiation-mobile#5]
le GPS reste en orange meme lorsque la precision est bonne (vue sur d'autres applications).
parfois l'appli voit 0,0 de lat long alorsq ue d'autres applis ont une localisation
il faudrait essayer de décaler les parametres de bornes pour l'orange et le vert, pour que ça soit beaucoup plus facile de les atteindre (on resserera plus tard le cas échéant)

**Comment by vm-agoralogie** [comment]
Actuellement : 
Rouge, pas de connexion réussie au gps via le plugin (message d'erreur suivant le retour : non autorisée, non activée, non disponible)
Orange si valeur accuracy > 5, vert en-dessous
Me donner la valeur à comparer pour accuracy

Corrections effectuées pour une meilleure persistance des données de position (long/lat)
